name: green_eats_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  dio: ^4.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_modular: ^5.0.3
  flutter_svg: ^1.1.6
  hive: ^2.2.3
  pretty_dio_logger: ^1.2.0-beta-1
  badges: ^3.1.2
  intl: ^0.18.1
  hive_flutter: ^1.1.0
  build_runner: 
  hive_generator: 
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"

